<<<<<<< HEAD
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dc66441e8276e2dd77766181b6e39a3a"
name = "remix-app-test"
application_url = "https://shopify-custom-remix-app.onrender.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
=======
client_id = "dc66441e8276e2dd77766181b6e39a3a"
name = "remix-app-test"
application_url = "https://lilly-unnative-uncontingently.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = false
>>>>>>> 34b6c67dfedb3fb6360572de469f9480b507938f

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
<<<<<<< HEAD
  uri = "https://lilly-unnative-uncontingently.ngrok-free.dev/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "https://lilly-unnative-uncontingently.ngrok-free.dev/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,read_inventory,read_locations,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify-custom-remix-app.onrender.com/auth/callback",
  "https://shopify-custom-remix-app.onrender.com/auth/shopify/callback"
]

[app_proxy]
url = "https://shopify-custom-remix-app.onrender.com"
=======
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations"

[auth]
redirect_urls = [ "https://lilly-unnative-uncontingently.ngrok-free.dev/api/auth" ]

[app_proxy]
url = "https://lilly-unnative-uncontingently.ngrok-free.dev"
>>>>>>> 34b6c67dfedb3fb6360572de469f9480b507938f
subpath = "notify"
prefix = "apps"
